name: simple_permissions
description: A new flutter plugin project.
version: 1.1.1
author: John Melody me 
homepage: https://github.com/johnmelodyme/simple_permissions

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
  
flutter:
  plugin:
    androidPackage: com.ethras.simplepermissions
    pluginClass: SimplePermissionsPlugin
